"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CSUC__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CSUC__factory_1 = require("./CSUC__factory");
Object.defineProperty(exports, "CSUC__factory", { enumerable: true, get: function () { return CSUC__factory_1.CSUC__factory; } });
