"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CurvyAggregator__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CurvyAggregator__factory_1 = require("./CurvyAggregator__factory");
Object.defineProperty(exports, "CurvyAggregator__factory", { enumerable: true, get: function () { return CurvyAggregator__factory_1.CurvyAggregator__factory; } });
