/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CurvyAggregator_Types {
  export type NoteStruct = {
    ownerHash: BigNumberish;
    token: BigNumberish;
    amount: BigNumberish;
  };

  export type NoteStructOutput = [
    ownerHash: bigint,
    token: bigint,
    amount: bigint
  ] & { ownerHash: bigint; token: bigint; amount: bigint };

  export type NoteWithMetaDataStruct = {
    note: CurvyAggregator_Types.NoteStruct;
    sender: AddressLike;
    deadline: BigNumberish;
    included: boolean;
    cancelled: boolean;
  };

  export type NoteWithMetaDataStructOutput = [
    note: CurvyAggregator_Types.NoteStructOutput,
    sender: string,
    deadline: bigint,
    included: boolean,
    cancelled: boolean
  ] & {
    note: CurvyAggregator_Types.NoteStructOutput;
    sender: string;
    deadline: bigint;
    included: boolean;
    cancelled: boolean;
  };

  export type ActionExecutionZKPStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
    inputs: BigNumberish[];
  };

  export type ActionExecutionZKPStructOutput = [
    a: [bigint, bigint],
    b: [[bigint, bigint], [bigint, bigint]],
    c: [bigint, bigint],
    inputs: bigint[]
  ] & {
    a: [bigint, bigint];
    b: [[bigint, bigint], [bigint, bigint]];
    c: [bigint, bigint];
    inputs: bigint[];
  };

  export type WrappingZKPStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
    inputs: BigNumberish[];
  };

  export type WrappingZKPStructOutput = [
    a: [bigint, bigint],
    b: [[bigint, bigint], [bigint, bigint]],
    c: [bigint, bigint],
    inputs: bigint[]
  ] & {
    a: [bigint, bigint];
    b: [[bigint, bigint], [bigint, bigint]];
    c: [bigint, bigint];
    inputs: bigint[];
  };

  export type UnwrappingZKPStruct = {
    a: [BigNumberish, BigNumberish];
    b: [[BigNumberish, BigNumberish], [BigNumberish, BigNumberish]];
    c: [BigNumberish, BigNumberish];
    inputs: BigNumberish[];
  };

  export type UnwrappingZKPStructOutput = [
    a: [bigint, bigint],
    b: [[bigint, bigint], [bigint, bigint]],
    c: [bigint, bigint],
    inputs: bigint[]
  ] & {
    a: [bigint, bigint];
    b: [[bigint, bigint], [bigint, bigint]];
    c: [bigint, bigint];
    inputs: bigint[];
  };

  export type ConfigurationUpdateStruct = {
    insertionVerifier: AddressLike;
    aggregationVerifier: AddressLike;
    withdrawVerifier: AddressLike;
    operator: AddressLike;
    feeCollector: AddressLike;
    withdrawBps: BigNumberish;
    csuc: AddressLike;
  };

  export type ConfigurationUpdateStructOutput = [
    insertionVerifier: string,
    aggregationVerifier: string,
    withdrawVerifier: string,
    operator: string,
    feeCollector: string,
    withdrawBps: bigint,
    csuc: string
  ] & {
    insertionVerifier: string;
    aggregationVerifier: string;
    withdrawVerifier: string;
    operator: string;
    feeCollector: string;
    withdrawBps: bigint;
    csuc: string;
  };
}

export interface CurvyAggregatorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "UPGRADE_INTERFACE_VERSION"
      | "aggregationVerifier"
      | "collectFees"
      | "csuc"
      | "feeCollector"
      | "feeCollectorBalances"
      | "getNoteInfo"
      | "initialize"
      | "insertionVerifier"
      | "noteTree"
      | "nullifierTree"
      | "operator"
      | "operatorExecute"
      | "owner"
      | "processWraps"
      | "proxiableUUID"
      | "renounceOwnership"
      | "transferOwnership"
      | "unwrap"
      | "updateConfig"
      | "upgradeToAndCall"
      | "withdrawBps"
      | "withdrawRejected"
      | "withdrawVerifier"
      | "wrapERC20"
      | "wrapNative"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "Initialized"
      | "OwnershipTransferred"
      | "UnwrappingToken"
      | "Upgraded"
      | "WrappingToken"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "aggregationVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "collectFees",
    values: [AddressLike[], AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "csuc", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "feeCollector",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "feeCollectorBalances",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getNoteInfo",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "insertionVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "noteTree", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "nullifierTree",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "operator", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "operatorExecute",
    values: [CurvyAggregator_Types.ActionExecutionZKPStruct]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "processWraps",
    values: [CurvyAggregator_Types.WrappingZKPStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "proxiableUUID",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unwrap",
    values: [CurvyAggregator_Types.UnwrappingZKPStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "updateConfig",
    values: [CurvyAggregator_Types.ConfigurationUpdateStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeToAndCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRejected",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawVerifier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "wrapERC20",
    values: [CurvyAggregator_Types.NoteStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "wrapNative",
    values: [CurvyAggregator_Types.NoteStruct[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "UPGRADE_INTERFACE_VERSION",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "aggregationVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "collectFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "csuc", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "feeCollector",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "feeCollectorBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNoteInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "insertionVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "noteTree", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "nullifierTree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "operator", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "operatorExecute",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "processWraps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proxiableUUID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unwrap", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateConfig",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeToAndCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRejected",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "wrapERC20", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "wrapNative", data: BytesLike): Result;
}

export namespace InitializedEvent {
  export type InputTuple = [version: BigNumberish];
  export type OutputTuple = [version: bigint];
  export interface OutputObject {
    version: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnwrappingTokenEvent {
  export type InputTuple = [
    to: AddressLike,
    token: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [to: string, token: string, amount: bigint];
  export interface OutputObject {
    to: string;
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpgradedEvent {
  export type InputTuple = [implementation: AddressLike];
  export type OutputTuple = [implementation: string];
  export interface OutputObject {
    implementation: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WrappingTokenEvent {
  export type InputTuple = [token: AddressLike, amount: BigNumberish];
  export type OutputTuple = [token: string, amount: bigint];
  export interface OutputObject {
    token: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CurvyAggregator extends BaseContract {
  connect(runner?: ContractRunner | null): CurvyAggregator;
  waitForDeployment(): Promise<this>;

  interface: CurvyAggregatorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  UPGRADE_INTERFACE_VERSION: TypedContractMethod<[], [string], "view">;

  aggregationVerifier: TypedContractMethod<[], [string], "view">;

  collectFees: TypedContractMethod<
    [_tokens: AddressLike[], _to: AddressLike],
    [boolean],
    "nonpayable"
  >;

  csuc: TypedContractMethod<[], [string], "view">;

  feeCollector: TypedContractMethod<[], [string], "view">;

  feeCollectorBalances: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getNoteInfo: TypedContractMethod<
    [_noteHash: BytesLike],
    [CurvyAggregator_Types.NoteWithMetaDataStructOutput],
    "view"
  >;

  initialize: TypedContractMethod<[], [void], "nonpayable">;

  insertionVerifier: TypedContractMethod<[], [string], "view">;

  noteTree: TypedContractMethod<[], [bigint], "view">;

  nullifierTree: TypedContractMethod<[], [bigint], "view">;

  operator: TypedContractMethod<[], [string], "view">;

  operatorExecute: TypedContractMethod<
    [_data: CurvyAggregator_Types.ActionExecutionZKPStruct],
    [boolean],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  processWraps: TypedContractMethod<
    [_data: CurvyAggregator_Types.WrappingZKPStruct],
    [boolean],
    "nonpayable"
  >;

  proxiableUUID: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unwrap: TypedContractMethod<
    [_data: CurvyAggregator_Types.UnwrappingZKPStruct],
    [boolean],
    "nonpayable"
  >;

  updateConfig: TypedContractMethod<
    [_update: CurvyAggregator_Types.ConfigurationUpdateStruct],
    [boolean],
    "nonpayable"
  >;

  upgradeToAndCall: TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;

  withdrawBps: TypedContractMethod<[], [bigint], "view">;

  withdrawRejected: TypedContractMethod<
    [_noteHash: BytesLike],
    [boolean],
    "nonpayable"
  >;

  withdrawVerifier: TypedContractMethod<[], [string], "view">;

  wrapERC20: TypedContractMethod<
    [_notes: CurvyAggregator_Types.NoteStruct[]],
    [boolean],
    "nonpayable"
  >;

  wrapNative: TypedContractMethod<
    [_notes: CurvyAggregator_Types.NoteStruct[]],
    [boolean],
    "payable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "UPGRADE_INTERFACE_VERSION"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "aggregationVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "collectFees"
  ): TypedContractMethod<
    [_tokens: AddressLike[], _to: AddressLike],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "csuc"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeCollector"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "feeCollectorBalances"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNoteInfo"
  ): TypedContractMethod<
    [_noteHash: BytesLike],
    [CurvyAggregator_Types.NoteWithMetaDataStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "insertionVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "noteTree"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nullifierTree"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "operator"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "operatorExecute"
  ): TypedContractMethod<
    [_data: CurvyAggregator_Types.ActionExecutionZKPStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "processWraps"
  ): TypedContractMethod<
    [_data: CurvyAggregator_Types.WrappingZKPStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "proxiableUUID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unwrap"
  ): TypedContractMethod<
    [_data: CurvyAggregator_Types.UnwrappingZKPStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateConfig"
  ): TypedContractMethod<
    [_update: CurvyAggregator_Types.ConfigurationUpdateStruct],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeToAndCall"
  ): TypedContractMethod<
    [newImplementation: AddressLike, data: BytesLike],
    [void],
    "payable"
  >;
  getFunction(
    nameOrSignature: "withdrawBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawRejected"
  ): TypedContractMethod<[_noteHash: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawVerifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "wrapERC20"
  ): TypedContractMethod<
    [_notes: CurvyAggregator_Types.NoteStruct[]],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "wrapNative"
  ): TypedContractMethod<
    [_notes: CurvyAggregator_Types.NoteStruct[]],
    [boolean],
    "payable"
  >;

  getEvent(
    key: "Initialized"
  ): TypedContractEvent<
    InitializedEvent.InputTuple,
    InitializedEvent.OutputTuple,
    InitializedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "UnwrappingToken"
  ): TypedContractEvent<
    UnwrappingTokenEvent.InputTuple,
    UnwrappingTokenEvent.OutputTuple,
    UnwrappingTokenEvent.OutputObject
  >;
  getEvent(
    key: "Upgraded"
  ): TypedContractEvent<
    UpgradedEvent.InputTuple,
    UpgradedEvent.OutputTuple,
    UpgradedEvent.OutputObject
  >;
  getEvent(
    key: "WrappingToken"
  ): TypedContractEvent<
    WrappingTokenEvent.InputTuple,
    WrappingTokenEvent.OutputTuple,
    WrappingTokenEvent.OutputObject
  >;

  filters: {
    "Initialized(uint64)": TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;
    Initialized: TypedContractEvent<
      InitializedEvent.InputTuple,
      InitializedEvent.OutputTuple,
      InitializedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "UnwrappingToken(address,address,uint256)": TypedContractEvent<
      UnwrappingTokenEvent.InputTuple,
      UnwrappingTokenEvent.OutputTuple,
      UnwrappingTokenEvent.OutputObject
    >;
    UnwrappingToken: TypedContractEvent<
      UnwrappingTokenEvent.InputTuple,
      UnwrappingTokenEvent.OutputTuple,
      UnwrappingTokenEvent.OutputObject
    >;

    "Upgraded(address)": TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;
    Upgraded: TypedContractEvent<
      UpgradedEvent.InputTuple,
      UpgradedEvent.OutputTuple,
      UpgradedEvent.OutputObject
    >;

    "WrappingToken(address,uint256)": TypedContractEvent<
      WrappingTokenEvent.InputTuple,
      WrappingTokenEvent.OutputTuple,
      WrappingTokenEvent.OutputObject
    >;
    WrappingToken: TypedContractEvent<
      WrappingTokenEvent.InputTuple,
      WrappingTokenEvent.OutputTuple,
      WrappingTokenEvent.OutputObject
    >;
  };
}
